import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { Position } from "@/types";
import type { ComplianceEvaluationResult } from "./compliance-rules-engine";
import type { BreachCalculation } from "@/types";

export async function generate13FPdfDraft(options: {
  position: Position;
  compliance: ComplianceEvaluationResult | null;
  calculation: BreachCalculation | null;
}) {
  const { position, compliance, calculation } = options;

  const formLabel = compliance?.requiredForm || "Schedule 13F";

  const pdfDoc = await PDFDocument.create();
  const page = pdfDoc.addPage([595.28, 841.89]); // A4
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const boldFont = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

  let y = 800;

  const drawText = (
    text: string,
    opts: {
      x?: number;
      y?: number;
      size?: number;
      bold?: boolean;
      color?: { r: number; g: number; b: number };
    } = {}
  ) => {
    const { x = 50, y: yPos, size = 10, bold = false, color } = opts;
    const useFont = bold ? boldFont : font;
    page.drawText(text, {
      x,
      y: yPos ?? y,
      size,
      font: useFont,
      color: color ? rgb(color.r, color.g, color.b) : rgb(0, 0, 0),
    });
    if (!yPos) {
      y -= size + 4;
    }
  };

  // Header
  page.drawRectangle({
    x: 0,
    y: 790,
    width: 595.28,
    height: 40,
    color: rgb(0.07, 0.11, 0.2),
  });
  drawText(`REGULATORY FILING DRAFT – ${formLabel}`, {
    x: 50,
    y: 812,
    size: 11,
    bold: true,
    color: { r: 1, g: 1, b: 1 },
  });
  drawText("INSTITUTIONAL INVESTMENT MANAGER DISCLOSURE", {
    x: 50,
    y: 798,
    size: 11,
    bold: true,
    color: { r: 1, g: 1, b: 1 },
  });

  y = 765;

  drawText("DRAFT ONLY – NOT FOR FILING", { bold: true, size: 9 });
  drawText(`Prepared: ${new Date().toISOString()}`, { size: 8 });

  y -= 10;

  // Manager / Issuer block
  drawText("Reporting Manager (Simulated): Global Regulatory Risk Engine", {
    bold: true,
  });
  drawText(`Issuer: ${position.issuer}`);
  drawText(`ISIN: ${position.isin}`);
  drawText(`Jurisdiction: ${position.jurisdiction}`);

  y -= 6;

  drawText("Position Snapshot:", { bold: true });
  drawText(
    `Current Position: ${position.currentPosition.toFixed(2)}% of outstanding class`
  );
  drawText(
    `Applicable Threshold: ${position.threshold.toFixed(2)}% per jurisdictional rule`
  );
  drawText(
    `Buying Velocity: ${position.buyingVelocity.toLocaleString()} shares/hr`
  );

  y -= 6;

  // Regulatory analysis
  drawText("Regulatory Analysis:", { bold: true });
  if (compliance) {
    drawText(`Status: ${compliance.status}`);
    drawText(`Required Filing Form: ${compliance.requiredForm}`);
    drawText(`Regulatory Deadline: ${compliance.deadline}`);
  } else {
    drawText("Status: SAFE – No filing obligation simulated for this position.");
  }

  if (calculation) {
    drawText(
      `Predictive Breach Engine: ${calculation.timeToBreach} (projected breach time string)`
    );
    if (calculation.projectedBreachTime !== null) {
      drawText(
        `Projected Time to Breach Threshold: ${calculation.projectedBreachTime.toFixed(
          2
        )} hours (under constant flow assumptions)`
      );
    }
  }

  y -= 6;

  // Tabular-style summary
  drawText(`Summary of Reportable Position (Simulated ${formLabel} Line Item):`, {
    bold: true,
  });
  drawText(
    "Class of Security: Common Stock                    Voting Authority: Sole (simulated)",
    { size: 9 }
  );
  drawText(
    "CUSIP / ISIN: See above                            Investment Discretion: Discretionary",
    { size: 9 }
  );

  y -= 6;

  drawText(
    "This draft is automatically generated by the Global Regulatory Risk Engine for review by Compliance.",
    { size: 8 }
  );
  drawText(
    `It is intended to approximate the structure and content of a ${formLabel} line item, but does not constitute legal advice.`,
    { size: 8 }
  );

  y -= 12;

  // Signature block
  drawText("Signature (Simulated):", { bold: true });
  drawText("Name: ____________________________", { size: 9 });
  drawText("Title: _____________________________", { size: 9 });
  drawText("Date: _____________________________", { size: 9 });

  const pdfBytes = await pdfDoc.save();
  // Uint8Array is compatible with Blob, but TypeScript needs explicit typing
  const blob = new Blob([pdfBytes as unknown as BlobPart], { type: "application/pdf" });
  const url = URL.createObjectURL(blob);

  const link = document.createElement("a");
  link.href = url;
  const safeForm = formLabel.replace(/[^a-zA-Z0-9]+/g, "-");
  link.download = `${safeForm}-draft-${position.issuer.replace(/\\s+/g, "-")}.pdf`;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}


